### ISSUE TITLE
[BUG] Localization not implemented for ColorPicker/Option

### ISSUE THREAD

**Issue by Nilon123456789** [dheid/colorpicker#54]
**Describe the bug**
The `ColorPicker` class is not using localization. 

**Code snippets**
```java
ResourceBundle.getBundle("com.bric.colorpicker.resources.ColorPicker"); // This is not calling the getBundle with a local.
```

**Expected behavior**
```java
ResourceBundle.getBundle("com.bric.colorpicker.resources.ColorPicker", local); // local being the current active localization
```

**Comment by dheid** [comment]
Thx for opening this issue! I will look at it, when I have time.

**Comment by Nilon123456789** [comment]
Alright, I might if I have time make a pull request with a fix ready

**Comment by Nilon123456789** [comment]
I've created a pull request with a working fix. Feel free to edit it or suggest me modifications.

**Comment by dheid** [comment]
Thx so much! New release 2.0.0 with your contribution is on it's way.
