### ISSUE TITLE
[BUG] Install error: JVMTest.checksWhetherSystemIsMac:23 

### ISSUE THREAD

**Issue by brandesNW** [dheid/colorpicker#56]
**Describe the bug**
In bash terminal, MacOS 14.3.1,  17.0.10+13-LTS
I type `mvn install` and get 

> [INFO] Running com.bric.colorpicker.JVMTest
> [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.031 s <<< FAILURE! -- in com.bric.colorpicker.JVMTest
> [ERROR] com.bric.colorpicker.JVMTest.checksWhetherSystemIsMac -- Time elapsed: 0.020 s <<< FAILURE!
> org.opentest4j.AssertionFailedError: 
> 
> Expecting value to be false but was true
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at com.bric.colorpicker.JVMTest.checksWhetherSystemIsMac(JVMTest.java:23)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   JVMTest.checksWhetherSystemIsMac:23 
> Expecting value to be false but was true
> [INFO] 
> [ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0

**Expected behavior**
The build completes with no test failures

**Additional context**
I also got a failure when using Java 1.8.0_292-b10

**Comment by dheid** [comment]
Thanks for opening this issue!

**Comment by dheid** [comment]
What a stupid mistake from my side: The test was always failing on Mac although the functionality was correct. :sweat: 

Fixed that. Thanks for telling me!
